### ISSUE TITLE
Default config is not working as expected - Mnemonic validation is failing

### ISSUE THREAD

**Issue by leohhhn** [gnolang/faucet#31]
## Description

In the current state of the faucet, following the README, building and running `faucet serve` will not work, as it seems that the default mnemonic is wrong, or its validation is failing for some reason. 

```
❯ ./build/faucet serve
unable to create faucet, invalid configuration, invalid mnemonic
```

Seems that [this line](https://github.com/gnolang/faucet/blob/58d6a69ca08b772f969f69bcdb0df9605585ee96/config/config.go#L87) is causing the issue. The default mnemonic is the `test1` mnemonic.

Trying a fresh mnemonic also fails with the same error, leading me to believe that the validation is failing for some reason.

**Comment by zivkovicmilos** [comment]
Have you try specifying an explicit mnemonic?

By default it's empty:
https://github.com/gnolang/faucet/blob/58d6a69ca08b772f969f69bcdb0df9605585ee96/cmd/serve.go#L103
